version: "3.7"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes: 
      - ../schema/:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: jimmy
      MYSQL_PASSWORD: 12345678
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
  app:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        VARIANT: "5.0"
    volumes:
      - ..:/workspace:cached
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
     # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity



